<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>File Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .report-info {
            margin-bottom: 10px;
            font-size: 14px;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .table th,
        .table td {
            border: 1px solid black;
            padding: 5px;
            text-align: left;
        }

        .table th {
            background-color: #f2f2f2;
        }

        .footer {
            margin-top: 20px;
            text-align: right;
            font-size: 12px;
        }
    </style>
</head>

<body>

    <div class="header">
        <h2>File Report</h2>
    </div>

    <div class="report-info">
        <p><strong>Generated by:</strong> {{ Auth::user()->name }}</p>
        <p><strong>Date Range:</strong> {{ $fromDate }} to {{ $toDate }}</p>
        <p><strong>Generated on:</strong> {{ now()->format('d-m-Y H:i:s') }}</p>
    </div>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>S/No</th>
                <th>File Open Date</th>
                <th>Ledger Ref</th>
                <th>Matter</th>
                <th>Client Name</th>
                <th>Address</th>
                <th>Fee Earner</th>
                <th>Status</th>
                <th>Close Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($files as $index => $record)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ date('d/m/Y', strtotime($record->File_Date)) }}</td>
                    <td>{{ $record->Ledger_Ref }}</td>
                    <td>{{ $record->Matter }}</td>
                    <td>{{ $record->First_Name }} {{ $record->Last_Name }}</td>
                    <td>{{ $record->Address1 }} {{ $record->Address2 }} {{ $record->Town }} {{ $record->Post_Code }}
                    </td>
                    <td>{{ $record->Fee_Earner }}</td>
                    <td>{{ $record->Status }}</td>
                    <td>{{ date('d/m/Y', strtotime($record->File_Date)) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>


    <div class="footer">
        <p>© {{ date('Y') }} Your Company Name. All rights reserved.</p>
    </div>

</body>

</html>
